### PR TITLE
Remove 'dead' codepoints for icons that were deprecated or renamed

### PR DESCRIPTION
**Pull request by spencer-nelson**

### CODE REVIEW

**Comment by aakash1313** [comment]
@spencer-nelson : I tested this one, it seems we need to remove the below code point as well :

Codepoint 61702 not found in font, aborting.

**Comment by spencer-nelson** [comment]
> @spencer-nelson : I tested this one, it seems we need to remove the below code point as well :
> 
> Codepoint 61702
> 
> Sorry, but can we rebase it too ?

Codepoint 61702 was Activity 24, which has been removed.

**Comment by aakash1313** [comment]
> > @spencer-nelson : I tested this one, it seems we need to remove the below code point as well :
> > Codepoint 61702
> > Sorry, but can we rebase it too ?
> 
> Codepoint 61702 was Activity 24, which has been removed.

@spencer-nelson : Could you please run the script to generate new icons with the updated file and push it ?

**Review by aakash1313 — APPROVED** [review]
Works as expected :)

**Pull request merged**
