### PR TITLE
Move react-native-svg from dependencies to peerDependencies

### PR DESCRIPTION
**Pull request by verluci**
React-native-svg is notorious for breaking things when there's multiple versions of the package installed. It's also very frequently required for packages. Listing it as a peerDependency prevents these issues. Other libraries from the Fluentui stack follow this approach as well, for example https://github.com/microsoft/fluentui-react-native/blob/main/packages/components/Icon/package.json

### CODE REVIEW

**Comment by verluci** [comment]
@microsoft-github-policy-service agree

**Comment by verluci** [comment]
Other libraries from the Fluentui stack follow this approach as well, for example https://github.com/microsoft/fluentui-react-native/blob/main/packages/components/Icon/package.json

**Comment by verluci** [comment]
Would you mind taking a look at this pr, @nickromano or @willhou?

**Comment by nickromano** [comment]
Hey @warren-ms can you please take a look?

**Review by tomi-msft — APPROVED** [review]

**Pull request merged**
