### PR TITLE
Adding 5G icon to new branch

### PR DESCRIPTION
**Pull request by tanmaya0102**
I added a Cellular 5G Icon in the assets folder to the repository. I am new to the open-source contribution. Please review and send any feedback or changes. I felt that 5G icon was missing, I made it myself using Adobe XD.

### CODE REVIEW

**Comment by spencer-nelson** [comment]
Thank you for your contribution. Most of the folks working with this project are currently out until after the New Year, but we will address this when people are back.

**Comment by tanmaya0102** [comment]
> Thank you for your contribution. Most of the folks working with this project are currently out until after the New Year, but we will address this when people are back.

Thank You So much.

**Comment by tanmaya0102** [comment]
Hi, Are the people back , So that they can review this?

**Comment by ItzLevvie** [comment]
some feedback:
1) the color used here is different
2) the font used here is different
3) seems like filled and regular are the same. They should be different (with different stroke length matching the ones that the 4G icon has)
4) the alignment of the word "5G" is several pixels to the left.

**Comment by jasoncuster** [comment]
Hey @tanmaya0102 - thanks for looking at this! It's looking pretty good though I agree with @ItzLevvie with notes - if you overlay you can see a few differences. Nothing big, but a few tweaks.

image

One thing to note is we're working on updating these with custom type in the next week hopefully. If they don't get done though, I'd love to add the shiny new 5g icon. I'll let you know what timing is like. We've also uploaded the guidelines if they help going forward. [Guidelines in Figma →](https://www.figma.com/community/file/836835755999342788/Microsoft-Fluent-System-Icons)

**Comment by tanmaya0102** [comment]
Thank You for your feedback, I will work on it and fix the issue

**Comment by jasoncuster** [comment]
@tanmaya0102 - As we were working on updating type we had the chance to get this one in. Sorry about the duplicate effort, keep the icons coming though!

**Pull request closed without merging**
